import { FORGE_NODE_TYPE, type ForgeNodeType } from '@magicborn/shared/types/forge-graph';

export const EXPORT_KIND = {
  YARN: 'YARN',
  RUNTIME_ONLY: 'RUNTIME_ONLY',
} as const;

export type ExportKind = typeof EXPORT_KIND[keyof typeof EXPORT_KIND];

export const NODE_EXPORT_KIND_REGISTRY = {
  [FORGE_NODE_TYPE.ACT]: EXPORT_KIND.RUNTIME_ONLY,
  [FORGE_NODE_TYPE.CHAPTER]: EXPORT_KIND.RUNTIME_ONLY,
  [FORGE_NODE_TYPE.PAGE]: EXPORT_KIND.RUNTIME_ONLY,
  [FORGE_NODE_TYPE.PLAYER]: EXPORT_KIND.YARN,
  [FORGE_NODE_TYPE.CHARACTER]: EXPORT_KIND.YARN,
  [FORGE_NODE_TYPE.CONDITIONAL]: EXPORT_KIND.YARN,
  [FORGE_NODE_TYPE.DETOUR]: EXPORT_KIND.YARN,
  [FORGE_NODE_TYPE.JUMP]: EXPORT_KIND.RUNTIME_ONLY,
  [FORGE_NODE_TYPE.END]: EXPORT_KIND.RUNTIME_ONLY,
  [FORGE_NODE_TYPE.STORYLET]: EXPORT_KIND.YARN,
} as const satisfies Record<ForgeNodeType, ExportKind>;

export const isRuntimeOnlyNodeType = (nodeType: ForgeNodeType): boolean =>
  NODE_EXPORT_KIND_REGISTRY[nodeType] === EXPORT_KIND.RUNTIME_ONLY;
