'use client';

import { useState } from 'react';
import { Plus, ChevronDown } from 'lucide-react';
import { Button } from '@/shared/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/shared/ui/dialog';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/shared/ui/dropdown-menu';
import { useProjects, useCreateProject, type ProjectDocument } from '@/app/lib/forge/queries';

interface ProjectSwitcherProps {
  selectedProjectId: number | null;
  onProjectChange: (projectId: number | null) => void;
}

export function ProjectSwitcher({ selectedProjectId, onProjectChange }: ProjectSwitcherProps) {
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [projectName, setProjectName] = useState('');
  const [projectDescription, setProjectDescription] = useState('');
  
  const projectsQuery = useProjects();
  const createProjectMutation = useCreateProject();
  
  const selectedProject = projectsQuery.data?.find(p => p.id === selectedProjectId);
  
  const handleCreateProject = async () => {
    if (!projectName.trim()) {
      return;
    }
    
    try {
      const projectData = {
        name: projectName.trim(),
        description: projectDescription.trim() || undefined,
        // Slug will be auto-generated by the beforeValidate hook
      };
      
      const createdProject = await createProjectMutation.mutateAsync(projectData);
      
      setIsCreateDialogOpen(false);
      setProjectName('');
      setProjectDescription('');
      onProjectChange(createdProject.id);
    } catch (error) {
      console.error('Failed to create project:', error);
    }
  };
  
  const handleProjectSelect = (project: ProjectDocument) => {
    onProjectChange(project.id);
  };
  
  return (
    <div className="flex items-center gap-2 border-b px-4 py-2 bg-background">
      <span className="text-sm font-medium text-muted-foreground">Project:</span>
      
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" className="min-w-[200px] justify-between">
            <span className="truncate">
              {selectedProject ? selectedProject.name : 'No project selected'}
            </span>
            <ChevronDown className="ml-2 h-4 w-4 shrink-0" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="start" className="min-w-[200px]">
          {projectsQuery.data?.map((project) => (
            <DropdownMenuItem
              key={project.id}
              onClick={() => handleProjectSelect(project)}
              className={selectedProjectId === project.id ? 'bg-accent' : ''}
            >
              {project.name}
            </DropdownMenuItem>
          ))}
          {projectsQuery.data?.length === 0 && (
            <DropdownMenuItem disabled>No projects found</DropdownMenuItem>
          )}
        </DropdownMenuContent>
      </DropdownMenu>
      
      <Button
        variant="ghost"
        size="icon"
        onClick={() => setIsCreateDialogOpen(true)}
        title="Create new project"
      >
        <Plus className="h-4 w-4" />
      </Button>
      
      <div className="ml-auto flex items-center gap-2">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => window.open('/admin', '_blank')}
          title="Open Payload Admin"
        >
          Admin
        </Button>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => window.open('/api/graphql-playground', '_blank')}
          title="Open GraphQL Playground (API Documentation)"
        >
          API
        </Button>
      </div>
      
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create New Project</DialogTitle>
            <DialogDescription>
              Create a new project to organize your dialogues, threads, and narrative content.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <label htmlFor="project-name" className="text-sm font-medium">
                Project Name *
              </label>
              <input
                id="project-name"
                type="text"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                placeholder="My Game Project"
              />
              <p className="text-xs text-muted-foreground">
                A slug will be automatically generated from the project name
              </p>
            </div>
            <div className="space-y-2">
              <label htmlFor="project-description" className="text-sm font-medium">
                Description
              </label>
              <textarea
                id="project-description"
                value={projectDescription}
                onChange={(e) => setProjectDescription(e.target.value)}
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 min-h-[80px] resize-y"
                placeholder="Optional description of your project..."
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setIsCreateDialogOpen(false);
                setProjectName('');
                setProjectDescription('');
              }}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreateProject}
              disabled={!projectName.trim() || createProjectMutation.isPending}
            >
              {createProjectMutation.isPending ? 'Creating...' : 'Create Project'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
