"use strict";
'use client';
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProjectSwitcher = ProjectSwitcher;
const react_1 = require("react");
const lucide_react_1 = require("lucide-react");
const button_1 = require("@/shared/ui/button");
const dialog_1 = require("@/shared/ui/dialog");
const dropdown_menu_1 = require("@/shared/ui/dropdown-menu");
const queries_1 = require("@/app/lib/forge/queries");
function ProjectSwitcher({ selectedProjectId, onProjectChange, writerMenus }) {
    const [isCreateDialogOpen, setIsCreateDialogOpen] = (0, react_1.useState)(false);
    const [projectName, setProjectName] = (0, react_1.useState)('');
    const [projectDescription, setProjectDescription] = (0, react_1.useState)('');
    const projectsQuery = (0, queries_1.useProjects)();
    const createProjectMutation = (0, queries_1.useCreateProject)();
    const selectedProject = projectsQuery.data?.find(p => p.id === selectedProjectId);
    const handleCreateProject = async () => {
        if (!projectName.trim()) {
            return;
        }
        try {
            const projectData = {
                name: projectName.trim(),
                description: projectDescription.trim() || undefined,
                // Slug will be auto-generated by the beforeValidate hook
            };
            const createdProject = await createProjectMutation.mutateAsync(projectData);
            setIsCreateDialogOpen(false);
            setProjectName('');
            setProjectDescription('');
            onProjectChange(createdProject.id);
        }
        catch (error) {
            console.error('Failed to create project:', error);
        }
    };
    const handleProjectSelect = (project) => {
        onProjectChange(project.id);
    };
    return (React.createElement("div", { className: "flex items-center gap-2 border-b px-4 py-2 bg-background" },
        React.createElement("span", { className: "text-sm font-medium text-muted-foreground" }, "Project:"),
        React.createElement(dropdown_menu_1.DropdownMenu, null,
            React.createElement(dropdown_menu_1.DropdownMenuTrigger, { asChild: true },
                React.createElement(button_1.Button, { variant: "outline", className: "min-w-[200px] justify-between" },
                    React.createElement("span", { className: "truncate" }, selectedProject ? selectedProject.name : 'No project selected'),
                    React.createElement(lucide_react_1.ChevronDown, { className: "ml-2 h-4 w-4 shrink-0" }))),
            React.createElement(dropdown_menu_1.DropdownMenuContent, { align: "start", className: "min-w-[200px]" },
                projectsQuery.data?.map((project) => (React.createElement(dropdown_menu_1.DropdownMenuItem, { key: project.id, onClick: () => handleProjectSelect(project), className: selectedProjectId === project.id ? 'bg-accent' : '' }, project.name))),
                projectsQuery.data?.length === 0 && (React.createElement(dropdown_menu_1.DropdownMenuItem, { disabled: true }, "No projects found")))),
        React.createElement(button_1.Button, { variant: "ghost", size: "icon", onClick: () => setIsCreateDialogOpen(true), title: "Create new project" },
            React.createElement(lucide_react_1.Plus, { className: "h-4 w-4" })),
        writerMenus && (React.createElement(React.Fragment, null,
            React.createElement(dropdown_menu_1.DropdownMenu, null,
                React.createElement(dropdown_menu_1.DropdownMenuTrigger, { asChild: true },
                    React.createElement(button_1.Button, { variant: "outline", className: "min-w-[120px] justify-between" },
                        React.createElement("div", { className: "flex items-center gap-2" },
                            React.createElement(lucide_react_1.Folder, { className: "h-4 w-4" }),
                            React.createElement("span", null, "File")),
                        React.createElement(lucide_react_1.ChevronDown, { className: "ml-2 h-4 w-4 shrink-0" }))),
                React.createElement(dropdown_menu_1.DropdownMenuContent, { align: "start" },
                    React.createElement(dropdown_menu_1.DropdownMenuSub, null,
                        React.createElement(dropdown_menu_1.DropdownMenuSubTrigger, null,
                            React.createElement(lucide_react_1.Download, { className: "mr-2 h-4 w-4" }),
                            "Download"),
                        React.createElement(dropdown_menu_1.DropdownMenuSubContent, null,
                            React.createElement(dropdown_menu_1.DropdownMenuItem, { onClick: writerMenus.onDownloadMarkdown, disabled: !writerMenus.canDownload },
                                React.createElement(lucide_react_1.FileText, { className: "mr-2 h-4 w-4" }),
                                "Markdown (.md)"),
                            React.createElement(dropdown_menu_1.DropdownMenuItem, { onClick: writerMenus.onDownloadPDF, disabled: !writerMenus.canDownload },
                                React.createElement(lucide_react_1.File, { className: "mr-2 h-4 w-4" }),
                                "PDF (.pdf)"))))),
            React.createElement(dropdown_menu_1.DropdownMenu, null,
                React.createElement(dropdown_menu_1.DropdownMenuTrigger, { asChild: true },
                    React.createElement(button_1.Button, { variant: "outline", className: "min-w-[120px] justify-between" },
                        React.createElement("div", { className: "flex items-center gap-2" },
                            React.createElement(lucide_react_1.Eye, { className: "h-4 w-4" }),
                            React.createElement("span", null, "View")),
                        React.createElement(lucide_react_1.ChevronDown, { className: "ml-2 h-4 w-4 shrink-0" }))),
                React.createElement(dropdown_menu_1.DropdownMenuContent, { align: "start" },
                    React.createElement(dropdown_menu_1.DropdownMenuItem, { onClick: writerMenus.onToggleFullWidth },
                        writerMenus.isFullWidth ? (React.createElement(lucide_react_1.Minimize2, { className: "mr-2 h-4 w-4" })) : (React.createElement(lucide_react_1.Maximize2, { className: "mr-2 h-4 w-4" })),
                        "Full width"))))),
        React.createElement("div", { className: "ml-auto flex items-center gap-2" },
            React.createElement(button_1.Button, { variant: "ghost", size: "sm", onClick: () => window.open('/admin', '_blank'), title: "Open Payload Admin" }, "Admin"),
            React.createElement(button_1.Button, { variant: "ghost", size: "sm", onClick: () => window.open('/api/graphql-playground', '_blank'), title: "Open GraphQL Playground (API Documentation)" }, "API")),
        React.createElement(dialog_1.Dialog, { open: isCreateDialogOpen, onOpenChange: setIsCreateDialogOpen },
            React.createElement(dialog_1.DialogContent, null,
                React.createElement(dialog_1.DialogHeader, null,
                    React.createElement(dialog_1.DialogTitle, null, "Create New Project"),
                    React.createElement(dialog_1.DialogDescription, null, "Create a new project to organize your dialogues, and narrative content.")),
                React.createElement("div", { className: "space-y-4 py-4" },
                    React.createElement("div", { className: "space-y-2" },
                        React.createElement("label", { htmlFor: "project-name", className: "text-sm font-medium" }, "Project Name *"),
                        React.createElement("input", { id: "project-name", type: "text", value: projectName, onChange: (e) => setProjectName(e.target.value), className: "w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2", placeholder: "My Game Project" }),
                        React.createElement("p", { className: "text-xs text-muted-foreground" }, "A slug will be automatically generated from the project name")),
                    React.createElement("div", { className: "space-y-2" },
                        React.createElement("label", { htmlFor: "project-description", className: "text-sm font-medium" }, "Description"),
                        React.createElement("textarea", { id: "project-description", value: projectDescription, onChange: (e) => setProjectDescription(e.target.value), className: "w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 min-h-[80px] resize-y", placeholder: "Optional description of your project..." }))),
                React.createElement(dialog_1.DialogFooter, null,
                    React.createElement(button_1.Button, { variant: "outline", onClick: () => {
                            setIsCreateDialogOpen(false);
                            setProjectName('');
                            setProjectDescription('');
                        } }, "Cancel"),
                    React.createElement(button_1.Button, { onClick: handleCreateProject, disabled: !projectName.trim() || createProjectMutation.isPending }, createProjectMutation.isPending ? 'Creating...' : 'Create Project'))))));
}
