export const writerTheme = {
  paragraph: 'leading-relaxed text-sm text-df-text-primary',
  heading: {
    h1: 'text-2xl font-semibold',
    h2: 'text-xl font-semibold',
    h3: 'text-lg font-semibold',
  },
  list: {
    ol: 'list-decimal pl-6',
    ul: 'list-disc pl-6',
    listitem: 'mb-1',
    listitemChecked: 'mb-1',
    listitemUnchecked: 'mb-1',
  },
  text: {
    bold: 'font-semibold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'rounded bg-df-surface px-1 py-0.5 font-mono text-[0.85em]',
    subscript: 'align-sub text-[0.75em]',
    superscript: 'align-super text-[0.75em]',
  },
  code: 'block whitespace-pre-wrap rounded-md bg-df-surface px-3 py-2 font-mono text-sm text-df-text-primary',
  codeHighlight: {
    atrule: 'text-sky-300',
    attr: 'text-emerald-300',
    boolean: 'text-emerald-300',
    builtin: 'text-emerald-300',
    cdata: 'text-df-text-tertiary',
    char: 'text-emerald-300',
    class: 'text-sky-300',
    comment: 'text-df-text-tertiary',
    constant: 'text-emerald-300',
    deleted: 'text-rose-300',
    doctype: 'text-df-text-tertiary',
    entity: 'text-emerald-300',
    function: 'text-sky-300',
    important: 'text-amber-300',
    inserted: 'text-emerald-300',
    keyword: 'text-amber-300',
    namespace: 'text-sky-300',
    number: 'text-emerald-300',
    operator: 'text-amber-300',
    prolog: 'text-df-text-tertiary',
    property: 'text-sky-300',
    punctuation: 'text-df-text-tertiary',
    regex: 'text-amber-300',
    selector: 'text-sky-300',
    string: 'text-emerald-300',
    symbol: 'text-emerald-300',
    tag: 'text-sky-300',
    url: 'text-emerald-300',
    variable: 'text-emerald-300',
  },
};
