import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    '../src/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages-shared/server-template/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'df-base': 'var(--color-df-base)',
        'df-surface': 'var(--color-df-surface)',
        'df-elevated': 'var(--color-df-elevated)',
        'df-node-bg': 'var(--color-df-node-bg)',
        'df-node-border': 'var(--color-df-node-border)',
        'df-node-selected': 'var(--color-df-node-selected)',
        'df-node-dimmed': 'var(--color-df-node-dimmed)',
        'df-npc-bg': 'var(--color-df-npc-bg)',
        'df-npc-border': 'var(--color-df-npc-border)',
        'df-npc-header': 'var(--color-df-npc-header)',
        'df-npc-text': 'var(--color-df-npc-text)',
        'df-npc-selected': 'var(--color-df-npc-selected)',
        'df-player-bg': 'var(--color-df-player-bg)',
        'df-player-border': 'var(--color-df-player-border)',
        'df-player-header': 'var(--color-df-player-header)',
        'df-player-text': 'var(--color-df-player-text)',
        'df-player-selected': 'var(--color-df-player-selected)',
        'df-conditional-bg': 'var(--color-df-conditional-bg)',
        'df-conditional-border': 'var(--color-df-conditional-border)',
        'df-conditional-header': 'var(--color-df-conditional-header)',
        'df-conditional-text': 'var(--color-df-conditional-text)',
        'df-start': 'var(--color-df-start)',
        'df-start-bg': 'var(--color-df-start-bg)',
        'df-end': 'var(--color-df-end)',
        'df-end-bg': 'var(--color-df-end-bg)',
        'df-edge-default': 'var(--color-df-edge-default)',
        'df-edge-default-hover': 'var(--color-df-edge-default-hover)',
        'df-edge-choice-1': 'var(--color-df-edge-choice-1)',
        'df-edge-choice-2': 'var(--color-df-edge-choice-2)',
        'df-edge-choice-3': 'var(--color-df-edge-choice-3)',
        'df-edge-choice-4': 'var(--color-df-edge-choice-4)',
        'df-edge-choice-5': 'var(--color-df-edge-choice-5)',
        'df-edge-loop': 'var(--color-df-edge-loop)',
        'df-edge-dimmed': 'var(--color-df-edge-dimmed)',
        'df-error': 'var(--color-df-error)',
        'df-error-bg': 'var(--color-df-error-bg)',
        'df-warning': 'var(--color-df-warning)',
        'df-warning-bg': 'var(--color-df-warning-bg)',
        'df-success': 'var(--color-df-success)',
        'df-success-bg': 'var(--color-df-success-bg)',
        'df-info': 'var(--color-df-info)',
        'df-info-bg': 'var(--color-df-info-bg)',
        'df-text-primary': 'var(--color-df-text-primary)',
        'df-text-secondary': 'var(--color-df-text-secondary)',
        'df-text-tertiary': 'var(--color-df-text-tertiary)',
        'df-text-muted': 'var(--color-df-text-muted)',
        'df-control-bg': 'var(--color-df-control-bg)',
        'df-control-border': 'var(--color-df-control-border)',
        'df-control-hover': 'var(--color-df-control-hover)',
        'df-control-active': 'var(--color-df-control-active)',
        'df-flag-dialogue': 'var(--color-df-flag-dialogue)',
        'df-flag-dialogue-bg': 'var(--color-df-flag-dialogue-bg)',
        'df-flag-quest': 'var(--color-df-flag-quest)',
        'df-flag-quest-bg': 'var(--color-df-flag-quest-bg)',
        'df-flag-achievement': 'var(--color-df-flag-achievement)',
        'df-flag-achievement-bg': 'var(--color-df-flag-achievement-bg)',
        'df-flag-item': 'var(--color-df-flag-item)',
        'df-flag-item-bg': 'var(--color-df-flag-item-bg)',
        'df-flag-stat': 'var(--color-df-flag-stat)',
        'df-flag-stat-bg': 'var(--color-df-flag-stat-bg)',
        'df-flag-title': 'var(--color-df-flag-title)',
        'df-flag-title-bg': 'var(--color-df-flag-title-bg)',
        'df-flag-global': 'var(--color-df-flag-global)',
        'df-flag-global-bg': 'var(--color-df-flag-global-bg)',
        'df-canvas-bg': 'var(--color-df-canvas-bg)',
        'df-canvas-grid': 'var(--color-df-canvas-grid)',
        'df-sidebar-bg': 'var(--color-df-sidebar-bg)',
        'df-sidebar-border': 'var(--color-df-sidebar-border)',
        'df-editor-bg': 'var(--color-df-editor-bg)',
        'df-editor-border': 'var(--color-df-editor-border)',
      },
    },
  },
  plugins: [],
};

export default config;

